import { AlertTriangle, Download, ShoppingBag, X } from "lucide-react";

export interface ShoppingListItem { itemId: string; name: string; unit: string; onHand: number; reserved?: number; available?: number; minLevel?: number; required: number; shortage: number; shortageReason?: "demand" | "minimum" | "both"; packageQuantity?: number; packagePrice?: number; unitCost?: number; }
export interface ShoppingListDrawerProps { isOpen: boolean; onClose: () => void; items?: readonly ShoppingListItem[]; onExportCsv?: () => void; }

export function ShoppingListDrawer({ isOpen, onClose, items = [], onExportCsv }: ShoppingListDrawerProps) {
  if (!isOpen) return null;
  const shortageItems = items.filter(item => item.shortage > 0);
  const exportCsv = () => {
    if (onExportCsv) return onExportCsv();
    const rows = shortageItems.map(item => [item.name, item.onHand, item.reserved ?? 0, item.available ?? item.onHand, item.required, item.shortage, item.shortageReason ?? "demand", item.unit].map(value => `"${String(value).replace(/"/g, '""')}"`).join(","));
    const link = document.createElement("a"); link.href = `data:text/csv;charset=utf-8,${encodeURIComponent([["Item", "On hand", "Reserved", "Available", "Required", "Shortage", "Reason", "Unit"].join(","), ...rows].join("\n"))}`; link.download = "shopping-list.csv"; link.click();
  };
  return <div className="fixed inset-0 z-50 bg-black/40" role="dialog" aria-modal="true" aria-labelledby="shopping-list-drawer-title"><aside className="ml-auto flex h-full w-full max-w-lg flex-col bg-[#FBF8F3] shadow-2xl"><header className="flex items-center justify-between border-b border-[#E5DDD3] bg-white px-5 py-4"><div className="flex gap-3"><ShoppingBag className="text-[#7A3E24]" /><div><h2 id="shopping-list-drawer-title" className="font-extrabold text-[#2F2925]">Shopping list</h2><p className="text-xs text-[#6F655E]">Available stock already excludes reservations.</p></div></div><button onClick={onClose} aria-label="Close shopping list" className="p-1"><X /></button></header><main className="flex-1 space-y-3 overflow-y-auto p-5">{shortageItems.length === 0 ? <p className="rounded-[14px] border border-[#E5DDD3] bg-white p-5 text-sm text-[#6F655E]">Everything required is available.</p> : shortageItems.map(item => <article key={item.itemId} className="rounded-[14px] border border-[#E5DDD3] bg-white p-4"><div className="flex justify-between gap-3"><div><h3 className="font-bold text-[#2F2925]">{item.name}</h3><p className="mt-1 text-xs text-[#6F655E]">On hand {item.onHand}{item.unit} · Reserved {item.reserved ?? 0}{item.unit} · Available <strong>{item.available ?? item.onHand}{item.unit}</strong></p></div><strong className="text-[#B8443C]">Buy {item.shortage}{item.unit}</strong></div><p className="mt-2 flex items-center gap-1 text-xs text-[#B8443C]"><AlertTriangle size={12} />{item.shortageReason === "minimum" ? "Below the minimum-level rule." : item.shortageReason === "both" ? "Scheduled demand and the minimum-level rule both contribute." : "Scheduled demand after reservations causes this shortage."} Required: {item.required}{item.unit}.</p></article>)}</main><footer className="flex justify-between border-t border-[#E5DDD3] bg-white p-4"><button onClick={onClose} className="font-bold text-[#6F655E]">Close</button><button onClick={exportCsv} disabled={!shortageItems.length} className="flex items-center gap-2 rounded-[10px] bg-[#7A3E24] px-4 py-2 text-sm font-bold text-white disabled:opacity-50"><Download size={15} />Export CSV</button></footer></aside></div>;
}
